# 8.0 References

Adde, A., Rey, P.-L., Brun, P., Külling, N., Fopp, F., Altermatt, F., Broennimann, O., Lehmann, A., Petitpierre, B., Zimmermann, N.E., Pellissier, L. and Guisan, A. 2023. N-SDM: a high-performance computing pipeline for Nested Species Distribution Modelling. Ecography, 2023: e0s6540.

Alberta Biodiversity Monitoring Institute. 2017. Alberta Wall-to-Wall Vegetation Layer Including “Backfilled” Vegetation in Human Footprints (Version 6). Alberta Biodiversity Monitoring Institute, Alberta, Canada. Report available at: abmi.ca. 

Hijmans, R., Phillips, S., Leathwick, J., and Elith, J. 2022. dismo: Species Distribution Modeling. R package version 1.3-8. [https://CRAN.R-project.org/package=dismo](https://CRAN.R-project.org/package=dismo)

Wang, T., A. Hamann, D. Spittlehouse, C. Carroll. 2016. Locally Downscaled and Spatially Customizable Climate Data for Historical and Future Periods for North America. PLoS One 11(6): e0156720 [https://doi.org/10.1371/journal.pone.0156720](https://doi.org/10.1371/journal.pone.0156720)
